language: node_js

notifications:
  email:
    on_success: never

cache:
  directories:
    - ~/.npm
    - node_modules

node_js:
  - 'node'
  - '11'
  - '10'

dist: trusty

sudo: required

before_script:
  - npm run lint

script:
  - npm run test:verbose

branches:
  only:
    - master
    - development
